---
hero_image: images/banner.png
listed: true
copyedit: false
title: Спіймай крапки
description: При реалізації цього проекту, ви навчитеся створювати гру, в якій потрібно буде ловити кольорові кульки стороною контролера-колеса такого ж кольору.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: З днем народження
  - 
    title: Create a controller
  - 
    title: Gain points or lose lives
  - 
    title: More dots
  - 
    title: Increase the difficulty
  - 
    title: 'Challenge: faster dots'
  - 
    title: Рекорд
  - 
    title: 'Завдання: вдоскональте свою гру!'
  - 
    title: Що далі?
