---
hero_image: images/banner.png
listed: true
copyedit: false
title: Vang de stippen
description: Leer hoe je een pakkend spel kunt maken.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Een controller maken
  - 
    title: 'Uitdaging: naar links draaien'
  - 
    title: Stippen verzamelen
  - 
    title: 'Uitdaging: meer stippen'
  - 
    title: 'Moeilijker maken'
  - 
    title: 'Uitdaging: sneller bewegende stippen'
  - 
    title: 'Topscore'
  - 
    title: 'Uitdaging: verbeter je spel!'
