---
hero_image: images/banner.png
listed: true
copyedit: false
title: Vang de stippen
description: Leer hoe je een stippen vang spel kunt maken
version: 4.0.0
last_tested: 2018/10/16
steps:
  - 
    title: Inleiding
  - 
    title: Een controller maken
  - 
    title: Verdien punten of verlies een leven
  - 
    title: Meer stippen
  - 
    title: Verhoog de moeilijkheid
  - 
    title: 'Uitdaging: sneller bewegende stippen'
  - 
    title: Topscore
  - 
    title: 'Uitdaging: verbeter je spel!'
  - 
    title: Wat kun je verder nog doen?
