---
hero_image: images/banner.png
listed: true
copyedit: false
title: Vang de stippen
description: Leer hoe je een pakkend spel kunt maken.
version: 4.0.0
last_tested: 2018/10/16
steps:
  - 
    title: Inleiding
  - 
    title: Een controller maken
  - 
    title: 'Uitdaging: naar links draaien'
  - 
    title: Stippen verzamelen
  - 
    title: 'Uitdaging: meer stippen'
  - 
    title: 'Moeilijker maken'
  - 
    title: Topscore
  - 
    title: 'Challenge: verbeter je spel!'
  - 
    title: Wat kun je verder nog doen?
