---
hero_image: images/banner.png
listed: true
copyedit: false
title: Catch the Dots
description: Learn how to make a dot-catching game.
version: 4.0.0
last_tested: 2018-10-16
steps:
- title: Introduction
- title: Creating a controller
- title: Collecting dots
- title: More dots
- title: Increasing the difficulty
- title: 'Challenge: Faster moving dots'
- title: High score
- title: 'Challenge: Improve your game!'
- title: 'Challenge: Game menu'
