---
hero_image: images/banner.png
theme:  turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Catch the Dots
description: Learn how to make a dot-catching game.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Creating a controller
- title: 'Challenge: Spinning left'
- title: Collecting dots
- title: 'Challenge: More dots'
- title: Increasing the difficulty
- title: 'Challenge: Faster moving dots'
- title: High score
- title: 'Challenge: Improve your game!'
- title: 'Challenge: Game menu'

