---
hero_image: images/banner.png
listed: true
copyedit: false
title: डॉट्स पकड़ें
description: डॉट-कैचिंग गेम बनाना सीखें
version: 4.0.0
last_tested: 2018-10-16
steps:
  - 
    title: भूमिका
  - 
    title: नियंत्रक बनाना
  - 
    title: 'चुनौती: बाईं तरफ घुमाना'
  - 
    title: डॉट्स एकत्र करना
  - 
    title: 'चुनौती: और बिंदु'
  - 
    title: 'कठिनाई बढ़ाना'
  - 
    title: 'चुनौती: तेज़ गति करने वाले बिंदु'
  - 
    title: 'उच्च स्कोर'
  - 
    title: 'चुनौती: अपने गेम में सुधार करें!'
