---
hero_image: images/banner.png
listed: true
copyedit: false
title: Apanha os pontos
description: Cria um jogo de apanhar-os-pontos
version: 4.0.0
last_tested: 2018-10-16
steps:
  - 
    title: Introdução
  - 
    title: Criar um controlador
  - 
    title: Ganhar pontos ou perder vidas
  - 
    title: Mais pontos
  - 
    title: Aumentar a dificuldade
  - 
    title: 'Desafio: pontos mais rápidos'
  - 
    title: Melhor pontuação
  - 
    title: 'Desafio: Melhorar o teu jogo!'
  - 
    title: O que se segue?
