---
hero_image: images/banner.png
listed: true
copyedit: false
title: Uhvati točke
description: U ovom projektu naučit ćeš kako kreirati igru u kojoj moraš uskladiti obojane točke s dijelovima kontrolera.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uhvati točke
  - 
    title: Create a controller
  - 
    title: Gain points or lose lives
  - 
    title: More dots
  - 
    title: Increase the difficulty
  - 
    title: 'Challenge: faster dots'
  - 
    title: High score
  - 
    title: 'Challenge: improve your game!'
  - 
    title: What next?
