---
hero_image: images/banner.png
listed: true
copyedit: false
title: Atrapa los Puntos
description: Aprende a crear un juego de unir puntos.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: Introducción
  - 
    title: Crear un controlador
  - 
    title: 'Desafío: Girar hacia la izquierda'
  - 
    title: Recoger puntos
  - 
    title: 'Desafío: Más puntos'
  - 
    title: 'Aumentar la dificultad'
  - 
    title: 'Reto: Crear más bloques'
  - 
    title: 'Desafío: mejora tu juego!'
  - 
    title: '¿Qué sigue?'
