---
hero_image: images/banner.png
listed: true
copyedit: false
title: Atrapa los Puntos
description: Haz un juego de atrapar puntos
version: 4.0.0
last_tested: 2018-10-16
steps:
  - 
    title: Introducción
  - 
    title: Crear un controlador
  - 
    title: Ganar puntos o perder vidas
    completion:
      - engaged
  - 
    title: Más puntos
  - 
    title: Aumentar la dificultad
  - 
    title: 'Desafío: Puntos que se mueven más rápido'
  - 
    title: Puntuación más alta
    completion:
      - internal
  - 
    title: 'Desafío: ¡Mejora tu juego!'
  - 
    title: What can you do now?
    completion:
      - external
