---
hero_image: images/banner.png
theme:  turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Atrapa los Puntos
description: Aprende a crear un juego de unir puntos.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Crear un controlador 
- title: 'Desafío: Girar hacia la izquierda'
- title: Recoger puntos
- title: 'Desafío: Más puntos'
- title: Aumentar la dificultad
- title: 'Desafío: Puntos que se mueven más rápido'
- title: Puntuación más alta
- title: 'Desafío: ¡Mejora tu juego!'
- title: 'Desafío: Menú del juego'

