---
hero_image: images/banner.png
listed: true
copyedit: false
title: Dal dotiau
description: Creu gêm i ddal dotiau
version: 4.0.0
last_tested: 2018-10-16
steps:
- title: Cyflwyniad
- title: Creu rheolwr
- title: Ennill pwyntiau neu cholli bywydau
  completion:
  - engaged
- title: Mwy o ddotiau
- title: Gwneud y gêm yn anoddach
- title: 'Her: dotiau cynt'
- title: Sgôr Uchel
  completion:
  - internal
- title: 'Her: gwella dy gêm!'
- title: Beth nesaf?
