---
hero_image: images/banner.png
listed: true
copyedit: false
title: Fange die Punkte
description: Lerne, wie man ein Fang-die-Punkte-Spiel herstellt.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Einen Controller herstellen
  - 
    title: 'Aufgabe: Nach links drehen'
  - 
    title: Punkte einsammeln
  - 
    title: 'Aufgabe: Noch mehr Punkte'
  - 
    title: 'Den Schwierigkeitsgrad steigern'
  - 
    title: 'Aufgabe: Sich schneller bewegende Punkte'
  - 
    title: 'Hohe Punktzahl'
  - 
    title: 'Aufgabe: Verbessere dein Spiel!'
