---
hero_image: images/banner.png
listed: true
copyedit: false
title: Fange die Punkte
description: Lerne, wie man ein Fang-die-Punkte-Spiel erstellt
version: 4.0.0
last_tested: 2018-10-16
steps:
  - 
    title: Einleitung
  - 
    title: Erstelle einen Controller
  - 
    title: Punkte sammeln oder Leben verlieren
    completion:
      - engaged
  - 
    title: Noch mehr Punkte
  - 
    title: Den Schwierigkeitsgrad steigern
  - 
    title: 'Herausforderung: Schnellere Punkte'
  - 
    title: Höchstpunktestand
    completion:
      - internal
  - 
    title: 'Herausforderung: Verbessere dein Spiel!'
  - 
    title: What can you do now?
    completion:
      - external
