---
hero_image: images/banner.png
listed: true
copyedit: false
title: Fange die Punkte
description: Lerne, wie man ein Fang-die-Punkte-Spiel herstellt.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: Einleitung
  - 
    title: Einen Controller herstellen
  - 
    title: 'Aufgabe: Nach links drehen'
  - 
    title: Punkte einsammeln
  - 
    title: 'Aufgabe: Noch mehr Punkte'
  - 
    title: 'Den Schwierigkeitsgrad steigern'
  - 
    title: Hohe Punktzahl
  - 
    title: 'Herausforderung: Erstelle mehr Blöcke!'
  - 
    title: 'Herausforderung: Ändere das Kostüm deiner Trommel'
