---
hero_image: images/banner.png
listed: true
copyedit: false
title: Catch the Dots
description: În acest proiect vei învăța cum să creezi un joc în care în care trebuie să potrivești punctele colorate cu partea corectă a controlerului.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Catch the Dots
  - 
    title: Create a controller
  - 
    title: Gain points or lose lives
  - 
    title: More dots
  - 
    title: Increase the difficulty
  - 
    title: 'Challenge: faster dots'
  - 
    title: High score
  - 
    title: 'Challenge: improve your game!'
  - 
    title: What next?
