---
hero_image: images/banner.png
listed: true
copyedit: false
title: Catch the Dots
description: În acest proiect vei învăța cum să creezi un joc în care în care trebuie să potrivești punctele colorate cu partea corectă a controlerului.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: Catch the Dots
  - 
    title: Creați un controler
  - 
    title: Obțineți puncte sau pierdeți vieți
  - 
    title: Mai multe puncte
  - 
    title: Creșteți dificultatea
  - 
    title: 'Provocare: puncte mai rapide'
  - 
    title: Cel mai mare scor
  - 
    title: 'Provocare: îmbunătățiți jocul!'
  - 
    title: Ce urmează?
