---
hero_image: images/banner.png
theme: turcoaz
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Prindeți punctele
description: În acest proiect vei învăța cum să creezi un joc în care în care trebuie să potrivești punctele colorate cu partea corectă a controlerului.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: jocuri
technologies: scratch
site_areas: proiecte
hardware: ''
software: scratch
version: 3
last_tested: 01-01-2017
steps:
  - 
    title: Catch the Dots
  - 
    title: Crearea unui controler
  - 
    title: 'Provocare: Invartirea la stanga'
  - 
    title: Colecteaza puncte
  - 
    title: 'Provocare: Mai multe puncte'
  - 
    title: Creste dificultatea
  - 
    title: 'Provocare: Puncte miscandu-se mai rapid'
  - 
    title: Top scor
  - 
    title: 'Provocare: Îmbunătățiți jocul!'
  - 
    title: 'Provocare: Meniul jocului'
