---
hero_image: images/banner.png
listed: true
copyedit: false
title: Capturando Bolinhas
description: Neste projeto vocês vão criar um jogo, no qual o jogador terá que capturar as bolinhas das diferentes cores com as partes certas de um controle redondo e colorido.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: Introdução
  - 
    title: Create a controller
  - 
    title: Gain points or lose lives
  - 
    title: More dots
  - 
    title: Increase the difficulty
  - 
    title: 'Challenge: faster dots'
  - 
    title: Recorde
  - 
    title: 'Desafio: melhore seu jogo!'
  - 
    title: E agora?
