---
hero_image: images/banner.png
listed: true
copyedit: false
title: Ujemi pike
description: Ustvari igro za lovjenje pik
version: 4.0.0
last_tested: 2018-10-16
steps:
- title: Uvod
- title: Ustvari krmilnik
- title: Pridobi točke ali izgubi življenje
  completion:
  - engaged
- title: Več pik
- title: Povečaj težavnost
- title: 'Izziv: hitrejše pike'
- title: Najboljši rezultat
  completion:
  - internal
- title: 'Izziv: izboljšaj igro!'