---
hero_image: images/banner.png
listed: true
copyedit: false
title: Atrapa los puntos
description: Haz un juego de atrapar puntos
version: 4.0.0
last_tested: 2018-10-16
steps:
- title: Introducción
- title: Crear un mando
- title: Gana puntos o pierde vidas
  completion:
  - engaged
- title: Más puntos
- title: Aumentar la dificultad
- title: 'Desafío: puntos más rápidos'
- title: Mejor puntaje
  completion:
  - internal
- title: 'Desafío: ¡mejora tu juego!'