---
hero_image: images/banner.png
listed: true
copyedit: false
title: جمع النقاط
description: تعلم كيف تصنع لعبة لجمع النقاط
version: 4.0.0
last_tested: 2018-10-16
steps:
- title: مقدمة
  completion: engaged
- title: إنشاء عجلة تحكم دوَّارة
- title: احصل على نقاط أو اخسر حياة
- title: نقاط أكثر
- title: زيادة الصعوبة
- title: 'التحدي: النقاط تتحرك أسرع'
- title: أعلى نتيجة
  completion: internal
- title: 'التحدي: تحسين لعبتك!'
- title: ما التالي؟
