---
hero_image: images/banner.png
listed: true
copyedit: false
title: Łapanie kropek
description: Naucz się, jak stworzyć grę, w której musisz dopasować kolorowe kulki do odpowiedniej części pokrętła.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Create a controller
  - 
    title: Gain points or lose lives
  - 
    title: More dots
  - 
    title: Increase the difficulty
  - 
    title: 'Challenge: faster dots'
  - 
    title: Tabela wyników
  - 
    title: 'Wyzwanie: udoskonal swoją grę!'
  - 
    title: Co następne?
