---
hero_image: images/banner.png
listed: true
copyedit: false
title: Łapanie kropek
description: Naucz się, jak stworzyć grę, w której musisz dopasować kolorowe kulki do odpowiedniej części pokrętła.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Create a controller
  - 
    title: Gain points or lose lives
  - 
    title: More dots
  - 
    title: Increase the difficulty
  - 
    title: 'Challenge: faster dots'
  - 
    title: High score
  - 
    title: 'Challenge: improve your game!'
  - 
    title: What next?
