---
hero_image: images/banner.png
theme: turkusowy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Złap kropki
description: Naucz się, jak stworzyć grę, w której musisz dopasować kolorowe kulki do odpowiedniej części pokrętła.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: gry
technologies: scratch
site_areas: projekty
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Łapanie kropek
  - 
    title: Tworzenie kontrolera
  - 
    title: 'Zakręć w lewo'
  - 
    title: Zbieraj kropki
  - 
    title: 'Wyzwanie: Więcej kropek'
  - 
    title: Zwiększenie trudności
  - 
    title: 'Wyzwanie: Szybciej poruszające się kropki'
  - 
    title: Tabela wyników
  - 
    title: 'Wyzwanie: udoskonal swoją grę!'
  - 
    title: 'Wyzwanie: Menu gry'
