---
hero_image: images/banner.png
listed: true
copyedit: false
title: Uhvati tačke
description: Nauči kako da napraviš igru hvatanja tačaka.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Izrada kontrolera
  - 
    title: 'Izazov: Okretanje ulijevo'
  - 
    title: Sakupljanje tačaka
  - 
    title: 'Izazov: Više tačaka'
  - 
    title: 'Povećavanje težine igre'
  - 
    title: 'Izazov: Tačke koje se brže kreću'
  - 
    title: 'Najbolji rezultat'
  - 
    title: 'Izazov: Poboljšaj svoju igru!'
