---
hero_image: images/banner.png
listed: true
copyedit: false
title: Uhvati tačke
description: Nauči kako da napraviš igru hvatanja tačaka.
version: 3
last_tested: 2018-10-16
steps:
  - 
    title: Uvod
  - 
    title: Izrada kontrolera
  - 
    title: 'Izazov: Okretanje ulijevo'
  - 
    title: Sakupljanje tačaka
  - 
    title: 'Izazov: Više tačaka'
  - 
    title: 'Povećavanje težine igre'
  - 
    title: Najbolji rezultat
  - 
    title: 'Izazov: poboljšaj svoju igru!'
  - 
    title: 'Izazov: promijeni kostim bubnja'
