---
hero_image: images/banner.png
theme:  turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Attrapes les points
description: Apprends à programmer un jeu où il faut attraper des points.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: "Création d'un contrôleur"
- title: 'Défi : Tourner à gauche'
- title: Rassemblement de points
- title: 'Défi : Plus de points'
- title: Augmentation de la difficulté
- title: 'Défi : Points plus rapides'
- title: Meilleur score
- title: 'Défi : Améliorez votre jeu!'

