---
hero_image: images / banner.png
listed: true
copyedit: false
title: Attrapes les points
description: Apprends à programmer un jeu où il faut attraper des points.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: introduction
  - 
    title: Création d'un contrôleur
  - 
    title: 'Défi : Tourner à gauche'
  - 
    title: Rassemblement de points
  - 
    title: 'Défi : Plus de points'
  - 
    title: 'Augmentation de la difficulté'
  - 
    title: 'Défi : Points plus rapides'
  - 
    title: 'Meilleur score'
  - 
    title: 'Défi : Améliorez votre jeu!'
