---
hero_image: images / banner.png
listed: true
copyedit: false
title: Acchiappa Puntini
description: Impara a creare un gioco acchiappa-puntini.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Creare un controller
  - 
    title: 'Sfida: Ruotare a sinistra'
  - 
    title: Raccogli puntini
  - 
    title: 'Sfida: Altri puntini'
  - 
    title: 'Aumenta la difficoltà'
  - 
    title: 'Sfida: Puntini che si muovono più velocemente'
  - 
    title: 'Punteggio alto'
  - 
    title: 'Sfida: Migliora il tuo gioco!'
