---
hero_image: images/banner.png
theme:  turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Acchiappa Puntini
description: Impara a creare un gioco acchiappa-puntini.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduzione
- title: Creare un controller
- title: 'Sfida: Ruotare a sinistra'
- title: Raccogli puntini
- title: 'Sfida: Altri puntini'
- title: Aumenta la difficoltà
- title: 'Sfida: Puntini che si muovono più velocemente'
- title: Punteggio alto
- title: 'Sfida: Migliora il tuo gioco!'
- title: 'Sfida: Menu partita'

