---
hero_image: images/banner.png
listed: true
copyedit: false
title: Cattura i puntini
description: Crea un gioco acchiappa puntini
version: 4.0.0
last_tested: 2018-10-16
steps:
  - 
    title: Introduzione
  - 
    title: Crea un controller
  - 
    title: Guadagna punti o perdi vite
    completion:
      - engaged
  - 
    title: Più puntini
  - 
    title: Aumenta la difficoltà
  - 
    title: 'Sfida: puntini più veloci'
  - 
    title: Punteggio alto
    completion:
      - internal
  - 
    title: 'Sfida: migliora il tuo gioco!'
  - 
    title: Cosa puoi fare adesso?
    completion:
      - external
