---
hero_image: images / banner.png
listed: true
copyedit: false
title: ඩොට්(dots) ඈල්ලීම
description: ඩොට් ඈල්ලීමේ සෙල්ලමක් නිර්මානය කිරිම
version: 4.0.0
last_tested: 2018-10-16
steps:
  - 
    title: හැදින්වීම
  - 
    title: පාලකයක් සෑකසීම
  - 
    title: පොයිට් ඈඩ් කර ගෑනීම හො අවස්තාවන් නෑති කර ගෑනීම
  - 
    title: තවත් ඩොට්
  - 
    title: අපහසු බව වෑඩි කර ගන්න
  - 
    title: 'අබියොගය : වේගවත් ඩොට්'
  - 
    title: වෑඩිම ලකුනු
  - 
    title: 'අබියොගය : ඔබේ ක්‍රීඩාව වෑඩි දියුනු කර ගන්න'
  - 
    title: ඊලඟට කුමක්ද?
